### ISSUE TITLE
Generování itemů do obchodu

### ISSUE THREAD

**Issue by davidkriz1** [Sognus/PVA_RP_2015#1]
Generování itemů do obchodu(jídlo, zbraně, brnění), ukládání do databáze na 8 hodin, poté se vygenerují nové

**Comment by Sognus** [comment]
První verze generování itemů dokončena, chtělo by to vypsat další úpravy, které je třeba provést.

**Comment by davidkriz1** [comment]
Chybí generování brnění a lektvarů s bonusy na útok a obranu v obchodu
